# Generated by Django 5.2 on 2025-05-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('category', models.CharField(choices=[('🥗 Starters', '🥗 Starters'), ('🍛 Main Course', '🍛 Main Course'), ('🍝 Noodles & Pasta', '🍝 Noodles & Pasta'), ('🍟 Sides', '🍟 Sides'), ('🍹 Drinks', '🍹 Drinks'), ('🍨 Desserts', '🍨 Desserts'), ('Healthy Foods', 'Healthy Foods')], default='🍹 Drinks', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=15)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem')),
            ],
        ),
    ]
