# Generated by Django 5.2 on 2025-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_item_order_menu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('rice', 'Rice'), ('chicken', 'Chicken'), ('beef', 'Beef'), ('mutton', 'Mutton'), ('fastfood', 'Fast Food'), ('drinks', 'Drinks')], default='fastfood', max_length=20),
        ),
    ]
