# Generated by Django 5.2 on 2025-05-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_item_order_menu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('rice', 'Rice'), ('fastfood', 'Fast Food'), ('drinks', 'Drinks')], default='rice', max_length=20),
        ),
    ]
