# Generated by Django 5.2 on 2025-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_item_order_menu_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('🥗 Starters', '🥗 Starters'), ('🍛 Main Course', '🍛 Main Course'), ('🍝 Noodles & Pasta', '🍝 Noodles & Pasta'), ('🍟 Sides', '🍟 Sides'), ('🍹 Drinks', '🍹 Drinks'), ('🍨 Desserts', '🍨 Desserts')], default='fastfood', max_length=20),
        ),
    ]
