# Generated by Django 5.2 on 2025-05-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_order_status_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
