# Generated by Django 5.2 on 2025-05-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('🥗 Starters', '🥗 Starters'), ('🍛 Main Course', '🍛 Main Course'), ('🍝 Noodles & Pasta', '🍝 Noodles & Pasta'), ('🍟 Sides', '🍟 Sides'), ('🍹 Drinks', '🍹 Drinks'), ('🍨 Desserts', '🍨 Desserts')], default='fastfood', max_length=20),
        ),
    ]
