# Generated by Django 5.2 on 2025-05-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_order_total_price_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
